production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: anagrams_development
  pool: 5
  host: localhost
  username: veronica
  password: pass
    
test:
  adapter: postgresql
  database: anagrams_test
  pool: 5
  host: localhost
  username: veronica
  password: pass
